### ISSUE TITLE
Running a profile which contains wrong OS

### ISSUE THREAD

**Issue by absolutejam** [hubblestack/hubble-salt#76]
Sorry for creating a few issues in rapid succession, but I wanted to get the points out there and hopefully I might be able to contribute to some of the more trivial ones.

I originally created this issue with the intent that when specfiying a profile that targets a different OS (Eg. using a RHEL profile on a Windows box), it should error/return a message. But upon further inspection, it looks like we can specify multiple OS in the same profile (In the `data` field).

So instead, would it be worth including a `skipped` section for the results, that explains the reason? Or could this be appended the `control` value?

Regards,
James.

**Comment by basepi** [comment]
Hmmm, an interesting idea. Profile targeting is a little bit of a mess. Originally I wrote them with the targeting in the profile, so you could have a single `cis_level1_scored.yaml` profile that would have all the different checks for the different operating systems in it. In that case, you definitely wouldn't want a `skipped` section, because it would be enormous, and full every time.

The paradigm that *actually* emerged was one where we have a separate file per operating system. I've been trying to decide if we want to double down on this paradigm and completely remove the targeting from the profile files to make them a little simpler, or if the old paradigm still has use cases.

Anyway, I'm rambling. The biggest hurdle for this feature is that hubble doesn't really pay attention to what was skipped. In fact, it takes the profiles that are specified and passes them into every nova module in order, with no expectation about whether that module will execute anything based on the data. So we would have to make hubble.py a lot smarter about paying attention to what's in the profile files, which would be a fairly big task for limited pay-off. I'm not sure it's worth it. Thoughts?

**Comment by absolutejam** [comment]
Well, I'd noticed that the example profiles all ended up moving towards specific OS, and I think it's a logical separation. I actually started with thinking that each profile should be OS-specific but as I started digging a bit, I liked the idea of being able to have different checks for each OS in one profile. Maybe it should be a top level meta key that can be overridden in specific checks?

So, currently each profile is split into the appropriate module and passed to the module, then the module returns a dict containing 'Success', 'Failed', and 'Controlled' back to the `hubble.py` for formatting, etc.? Perhaps the OS parsing should be, or would that be difficult due to the varying format of the configuration data?

I'm new to all of this, but I wonder if any of the boilerplate (eg. `_get_tags`) could be merged into a class that can just be imported and overridden - or do the modules vary too much between one-another for this to be a reality?

**Comment by basepi** [comment]
They're close, but not quite the same, especially once you get past the common patterns (like OS) at the upper levels of the data structure. I don't think they're abstractable to a separate module/class without some modification of the data format. I'm definitely open to suggestions about better ways to format the data.

In any case, it sounds like you understand the difficulties with the current way it's architected. We could potentially have each module report `skipped` and then use a set to remove duplicates afterwards. I'm still not sure that it would be that useful, though.

**Comment by basepi** [comment]
Since this hasn't had any momentum and we never came up with a good solution, I'm going to close it for now.
